apiVersion: v1
kind: ConfigMap
metadata:
  name: brandschutz-eder-config
  namespace: brandschutz-eder
  labels:
    app: brandschutz-eder
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  SPRING_PROFILES_ACTIVE: prod
  PORT: "8080"
  DB_HOST: postgres.postgres.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: brandschutz-eder
  JPA_DDL_AUTO: update
  JPA_SHOW_SQL: "false"
