apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: brandschutz-eder-secret
  namespace: brandschutz-eder
spec:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: AgCQ5qZZ7i94MO/o4k0aWSMtS5R7RbNVVmv2f38ksnqbRGDeQZbse8aZfcNh5YOMiq7d4xaFGqO+rro8Se44KdVJwbHWFjnDtvB4PRt0TFhvHn72GGJn+UxyYyJb6rBBRZ8ldSlPP2lnAh4Qa5Y30xgixAv5fjVhGZ5wj7PD/MjOLK4Rm6KlnQojn6MPqEo28ZrditBUB3k+D+5XMF19aCPaHNeiL23kPkWvEODPbTMeYBflOD4PLklkxj6TvgHn0dYPlczy3sDNb884mc41wlA8L7BlDSi01Y1l/rAKIvaGgZpnNJ/VLGVBXbs27TEqD1oEZaPSVCFgZoP5XjfAtQGdmMtEGAHuSRho43XdF2k2ivEWmzkw9WqEV5Vf8sFRjW4rD7D1EtsGAWYqKd5B8v/lQ1bTXabJlgrVaKS8Eli6+f5NsoXwqs1hh2cMgdsvBNOotb6kXwh/Q9iSM0R1t37VLypLTrsTIrcMU7XYOBwMrbXfMsSjjD8kPjwB+4hdG3y+9Wdgn2vch+pflkt8j37Qq6DIt1pt63LNjZI/kDrdIH6HBylqRBww8XDBkdLtfNtGmaZ0gNwyIOShaOPmODajbo7Ak5THX3sFEWJN3eumANmdQfuylqujXTtE1qL3RwGdULBZWzjlIC8THN+qjkfWcKf5clZB4KBwBEd3Hb9u93LkaMNKZoAYKuVw0wF1VDk5sbtCL5iha3JKGmD+Xv+SS5jBsA==
    SPRING_DATASOURCE_USERNAME: AgCJl4p4nI4Q98B2DgQwJ4FJ7rmfIB+6B7iE7xOgEHkFhtD1U6k1OWI6EdQYPCn2Hmj8QlAQSD0lWpvb0nAXyHtncVSo7Zmkc/6OYxZSpESqqBfp/n9+VTf7sIAw4pGhmK0BvuHRqJoOnsdti7icNFIrEdYso4l2yTi2OnfFpBKmI2BN2thhAhcIfkH+/fiI+A4LI6roC7FNZEKjTBALnQEFpVDgu9HM4XdsfbtvpYmbgxaXQq51t5Jp3Od67hBilslclbhNeBRN6+4pVumS0OOOtMfFKFbMaCp17HMJW21gs3hAKnlDLjxjK2UzJTz0QfBbu5f5KuVmooAn1CHNYHg6iG3Ii+XNqsEy+i6KIN4gYlx3Ir16YLXi8czhgsfzDSOVXgWSuBLBEZMio3YpGm3m86yCsIv2IOZWA7j6cGeaOc1F7M0+/eSXgmpP19K3KxTK4lSWRRo7B4DqJR98AkgU4KlmtP1HlLkyriJRUzOpZxlEzQ409payBaThXgxrdEHjpnCioSFMm9iefYyIV1mMr5+KBTpTv2SGR15wcD8tFSxPht7GQHJl/vtPpBRSuBMRGb6XuW6u+yFPloiFIZodRGVcwH62Py/eX2MUAtmNP+qP2K58xvaJk2hi7kymjJwF31+PIuhtC2U1dnvubt/Lkgc81juGVknVhwQLrKgOYFq1+O1PaV5qcByVqfw6ieHS64BIMx4xKnI94+y7+Di4ZbtWNOM=
  template:
    metadata:
      name: brandschutz-eder-secret
      namespace: brandschutz-eder
    type: Opaque
