apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: brandschutz-eder-secret
  namespace: brandschutz-eder
spec:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: AgBdEsNqREE4n8iYdmaWN3aJsrt/ldooWfIbrNmXEaA9YIi7vtTMknadSXWNsxKYSSeW+rflQ4WvT578WnqWGoBBoBuwUtcP9myUTPkxOESlum6KkPlmGRB9qfxzz/r1LG5vPwoogZbZrm665D9jucKzBanaBVQcFtMqaeiUfkcvDaSi1u0lGH8w5tkDhyMlrQC1hAYyEoBr7aWM8UGY+kG5IvQxbTvuoXCAyDAAQa/XiTYmbg744twEqAzxo+10NGZU78gg/T7Md/6RQOCxPrgSgDF6LFWCh4qrfYKZCInYQWssMG8UXglnCw9zVdCzIzh1ZJXQWI1SRsOdr1XYq4PRSK4OQNGTOo2JUjKlfeEMy6GfqilnietECCQwnkf/IDbVi+aB7gaN37yUlw4Nb/JMUIpqcdivlkYSA4tkkqyy1mqusUi8konBZf3MgjyguQjUP6Y00TXV+OoKXSuDG68EAFNNnssuGdxF8xE00eAr2ztEf6/wsrJAu53bXjNfw2dK4YVG7/lSH857YmYrbmV7wQ0DOordr+9S0ebglytABGSVdq+r5TZMbuUyEhIFfaHYSS4LjGRCrC+Eo8AmmqD6WwcVvIw0UIVZ8bMivTpr7hBh4FRXDiqpXEcxOxDLu47Ym1GlKQIBB4UFnUHg84osBhOkzNL5LT+HQ/0xEhUWDrv3ZWEsfVU6hdetdHbW48vc5vD2B1qzo3dqEyncOQ0K5JqkIQ==
    SPRING_DATASOURCE_USERNAME: AgC3ctRQnwrrLgk+aNofa7Liuo2Tf+21vfbo6hMXB3FAmbcGleAGzRqo0sbnW3By5zD33b5/33Sd75WT7hPPHsLU1QjRDRNQF6WVS1o/ZgPupuMSwq9P+FTkPqw8DCLRqMaCw9i8r66oU6Gx8MJoAXJnen1gM+qIGlSo+qzpiTHB3LIZcokUGYzjQpqy1QvLjvm/lxInxdCpQuU4mAkguB/tcH1c4Smt4dYOlpRtF0nLvJsZvSiB3lA2vrfwtY7PK+aGJSZm0P9BSEY1KP+/Ny6+X97tCiIGCiGJvv2YfbK96WEchijduK5EJug3LxX7+51x3rbev2GQJEoaFT4KDuRoMuCB4Ju8/FZ8k4pD0CllZbKJraM/06E1/4DjuwvqHkY3Wbd61onYt7Qwt7Fha1o8YiNlm0P32WOsUPcc3JLWO0LwVZDtxIdhLtofuQ/m+gcxcuEuYTg7DZbCOd7nXCMEVK/7IQmrOaELzdI4hq0ViFuzwbmROLqDnuThqrdfh0rjlGZFjVVUPMw3Md9sty64N9n5Ddhr7PJ46cjClj3xJpSi9JfugcUy92rFgd+FeZz7EWHXu6vrcWYMvBMz2CJ1/Op18uVQYGw1ZEn129yxCAPlHtKCEHYxuPs8CJuCBFwWVBQ4utcl8s4FQNHXASCY6vApBWstMNZKCFlwXlsfIT77XybjoRLMETwgJOeJvC3yJpGsGYLxFJUAigv+Y7S3hlD6Ho8=
  template:
    metadata:
      name: brandschutz-eder-secret
      namespace: brandschutz-eder
    type: Opaque
