apiVersion: v1
kind: Service
metadata:
  labels:
    app: brandschutz-eder
    app.kubernetes.io/name: brandschutz-eder
    app.kubernetes.io/component: backend
  name: brandschutz-eder-service
  namespace: brandschutz-eder
spec:
  type: ClusterIP
  selector:
    app: brandschutz-eder
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http